apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pomodolist-managed-cert-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: pomodolist-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: pomodolist-frontend-config
spec:
  defaultBackend:
    service:
      name: pomodolist-frontend-service
      port:
        number: 80